name: STWareIDEWebsite
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/

  fonts:
   - family: GoogleSans
     fonts:
       - asset: assets/fonts/GoogleSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/GoogleSans-BoldItalic.ttf
         style: italic
         weight: 700
       - asset: assets/fonts/GoogleSans-Italic.ttf
         style: italic
         weight: 400
       - asset: assets/fonts/GoogleSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/GoogleSans-MediumItalic.ttf
         style: italic
         weight: 500
       - asset: assets/fonts/GoogleSans-Regular.ttf
         weight: 400
  